-- https://lua.expert/
return {
	PremiumRewards = {
		[1] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "AKM"
		},
		[2] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "300",
			ID = "S2_2"
		},
		[3] = {
			Name = "Serpent Poison",
			Type = "Skin",
			Weapon = "SCAR-L"
		},
		[4] = {
			Name = "Magma",
			Type = "Top"
		},
		[5] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "1000",
			ID = "S2_5"
		},
		[6] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "AS VAL"
		},
		[7] = {
			Name = "Serpent Poison",
			Type = "Skin",
			Weapon = "MP7"
		},
		[8] = {
			Name = "Bullet",
			Type = "Charm"
		},
		[9] = {
			Name = "Magma",
			Type = "Bottom"
		},
		[10] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "AUG A3"
		},
		[11] = {
			Name = "Serpent Poison",
			Type = "Skin",
			Weapon = "P90"
		},
		[12] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "200",
			ID = "S2_12"
		},
		[13] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "Beretta M9"
		},
		[14] = {
			Name = "Magma",
			Type = "Head"
		},
		[15] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "700",
			ID = "S2_15"
		},
		[16] = {
			Name = "Serpent Poison",
			Type = "Skin",
			Weapon = "PP Bizon"
		},
		[17] = {
			Name = "Afterlink",
			Type = "Banner"
		},
		[18] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "Desert Eagle 50 AE"
		},
		[19] = {
			Name = "Instigator",
			Type = "Title"
		},
		[20] = {
			Name = "Serpent Poison",
			Type = "Skin",
			Weapon = "Serbu Shotgun"
		},
		[21] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "FAL"
		},
		[22] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "200",
			ID = "S2_22"
		},
		[23] = {
			Name = "Serpent Poison",
			Type = "Skin",
			Weapon = "TEC-9"
		},
		[24] = {
			Name = "Aqua",
			Type = "Top"
		},
		[25] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "700",
			ID = "S2_25"
		},
		[26] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "FAMAS"
		},
		[27] = {
			Name = "Serpent Poison",
			Type = "Skin",
			Weapon = "UMP45"
		},
		[28] = {
			Name = "Glare",
			Type = "Charm"
		},
		[29] = {
			Name = "Aqua",
			Type = "Bottom"
		},
		[30] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "G17"
		},
		[31] = {
			Name = "Serpent Poison",
			Type = "Skin",
			Weapon = "Vector"
		},
		[32] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "200",
			ID = "S2_32"
		},
		[33] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "G36C"
		},
		[34] = {
			Name = "Aqua",
			Type = "Head"
		},
		[35] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "700",
			ID = "S2_35"
		},
		[36] = {
			Name = "Serpent Poison",
			Type = "Skin",
			Weapon = "MP10"
		},
		[37] = {
			Name = "Esoteric",
			Type = "Banner"
		},
		[38] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "Honey Badger"
		},
		[39] = {
			Name = "Lethal",
			Type = "Title"
		},
		[40] = {
			Name = "Serpent Poison",
			Type = "Skin",
			Weapon = "AUG A2"
		},
		[41] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "M24"
		},
		[42] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "200",
			ID = "S2_42"
		},
		[43] = {
			Name = "Serpent Poison",
			Type = "Skin",
			Weapon = "M93R"
		},
		[44] = {
			Name = "Void Walker",
			Type = "Top"
		},
		[45] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "700",
			ID = "S2_45"
		},
		[46] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "MAC10"
		},
		[47] = {
			Name = "Serpent Poison",
			Type = "Skin",
			Weapon = "M45A1"
		},
		[48] = {
			Name = "Magma Crystal",
			Type = "Charm"
		},
		[49] = {
			Name = "Void Walker",
			Type = "Bottom"
		},
		[50] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "MP5"
		},
		[51] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "FN Minimi"
		},
		[52] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "200",
			ID = "S2_52"
		},
		[53] = {
			Name = "Serpent Poison",
			Type = "Skin",
			Weapon = "AS VAL"
		},
		[54] = {
			Name = "Void Walker",
			Type = "Head"
		},
		[55] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "700",
			ID = "S2_55"
		},
		[56] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "Vector"
		},
		[57] = {
			Name = "Serpent Poison",
			Type = "Skin",
			Weapon = "FN Minimi"
		},
		[58] = {
			Name = "Magma Crystal",
			Type = "Charm"
		},
		[59] = {
			Name = "Exosmoke",
			Type = "Banner"
		},
		[60] = {
			Name = "Isolation Carpet Gold",
			Type = "Skin",
			Weapon = "P90"
		},
		[61] = {
			Name = "Mythoscale Heat",
			Type = "Skin",
			Weapon = "AKM"
		},
		[62] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "300",
			ID = "S2_62"
		},
		[63] = {
			Name = "Veil",
			Type = "Skin",
			Weapon = "SCAR-L"
		},
		[64] = {
			Name = "Smoke",
			Type = "Top"
		},
		[65] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "1000",
			ID = "S2_65"
		},
		[66] = {
			Name = "Mythoscale Heat",
			Type = "Skin",
			Weapon = "AS VAL"
		},
		[67] = {
			Name = "Veil",
			Type = "Skin",
			Weapon = "MP7"
		},
		[68] = {
			Name = "Bullet",
			Type = "Charm"
		},
		[69] = {
			Name = "Smoke",
			Type = "Bottom"
		},
		[70] = {
			Name = "Mythoscale Heat",
			Type = "Skin",
			Weapon = "AUG A3"
		},
		[71] = {
			Name = "Veil",
			Type = "Skin",
			Weapon = "P90"
		},
		[72] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "200",
			ID = "S2_72"
		},
		[73] = {
			Name = "Mythoscale Heat",
			Type = "Skin",
			Weapon = "Beretta M9"
		},
		[74] = {
			Name = "Smoke",
			Type = "Head"
		},
		[75] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "700",
			ID = "S2_75"
		},
		[76] = {
			Name = "Veil",
			Type = "Skin",
			Weapon = "PP Bizon"
		},
		[77] = {
			Name = "Afterlink",
			Type = "Banner"
		},
		[78] = {
			Name = "Mythoscale Heat",
			Type = "Skin",
			Weapon = "Desert Eagle 50 AE"
		},
		[79] = {
			Name = "MAGMA",
			Type = "Title"
		},
		[80] = {
			Name = "Veil",
			Type = "Skin",
			Weapon = "Serbu Shotgun"
		},
		[81] = {
			Name = "Mythoscale Heat",
			Type = "Skin",
			Weapon = "FAL"
		},
		[82] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "200",
			ID = "S2_82"
		},
		[83] = {
			Name = "Veil",
			Type = "Skin",
			Weapon = "TEC-9"
		},
		[84] = {
			Name = "Grin",
			Type = "Top"
		},
		[85] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "700",
			ID = "S2_85"
		},
		[86] = {
			Name = "Mythoscale Heat",
			Type = "Skin",
			Weapon = "FAMAS"
		},
		[87] = {
			Name = "Veil",
			Type = "Skin",
			Weapon = "UMP45"
		},
		[88] = {
			Name = "Glare",
			Type = "Charm"
		},
		[89] = {
			Name = "Grin",
			Type = "Bottom"
		},
		[90] = {
			Name = "Mythoscale Heat",
			Type = "Skin",
			Weapon = "G17"
		},
		[91] = {
			Name = "Veil",
			Type = "Skin",
			Weapon = "Vector"
		},
		[92] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "200",
			ID = "S2_92"
		},
		[93] = {
			Name = "Mythoscale Heat",
			Type = "Skin",
			Weapon = "G36C"
		},
		[94] = {
			Name = "Grin",
			Type = "Head"
		},
		[95] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "700",
			ID = "S2_95"
		},
		[96] = {
			Name = "Veil",
			Type = "Skin",
			Weapon = "MP10"
		},
		[97] = {
			Name = "Esoteric",
			Type = "Banner"
		},
		[98] = {
			Name = "Mythoscale Heat",
			Type = "Skin",
			Weapon = "Honey Badger"
		},
		[99] = {
			Name = "Secure Agent",
			Type = "Title"
		},
		[100] = {
			Name = "Veil",
			Type = "Skin",
			Weapon = "AUG A2"
		},
		[101] = {
			Name = "Mythoscale Heat",
			Type = "Skin",
			Weapon = "M24"
		},
		[102] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "200",
			ID = "S2_102"
		},
		[103] = {
			Name = "Veil",
			Type = "Skin",
			Weapon = "M93R"
		},
		[104] = {
			Name = "Mythoscale Heat",
			Type = "Skin",
			Weapon = "FN Minimi"
		},
		[105] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "700",
			ID = "S2_105"
		},
		[106] = {
			Name = "Mythoscale Heat",
			Type = "Skin",
			Weapon = "MAC10"
		},
		[107] = {
			Name = "Veil",
			Type = "Skin",
			Weapon = "M45A1"
		},
		[108] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "500",
			ID = "S2_108"
		},
		[109] = {
			Name = "Veil",
			Type = "Skin",
			Weapon = "FN Minimi"
		},
		[110] = {
			Name = "Mythoscale Heat",
			Type = "Skin",
			Weapon = "MP5"
		},
		[115] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "100",
			ID = "S2_115"
		},
		[120] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "100",
			ID = "S2_120"
		},
		[125] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "100",
			ID = "S2_125"
		},
		[130] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "100",
			ID = "S2_130"
		}
	},
	FreeRewards = {
		[2] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "500",
			ID = "FreeS2_3"
		},
		[4] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_4"
		},
		[5] = {
			Name = "Arid",
			Type = "Skin",
			Weapon = "M4A1"
		},
		[8] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_8"
		},
		[9] = {
			Name = "Payback",
			Type = "Title"
		},
		[10] = {
			Name = "Corrupted",
			Type = "Head"
		},
		[12] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_12"
		},
		[13] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "500",
			ID = "FreeS2_13"
		},
		[15] = {
			Name = "Arid",
			Type = "Skin",
			Weapon = "AKM"
		},
		[16] = {
			Name = "Flask",
			Type = "Banner"
		},
		[19] = {
			Name = "Arid",
			Type = "Skin",
			Weapon = "FAL"
		},
		[20] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_20"
		},
		[21] = {
			Name = "Corrupted",
			Type = "Top"
		},
		[23] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "500",
			ID = "FreeS2_23"
		},
		[24] = {
			Name = "Cursed Dog",
			Type = "Charm"
		},
		[25] = {
			Name = "Arid",
			Type = "Skin",
			Weapon = "PPSh-41"
		},
		[28] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_28"
		},
		[29] = {
			Name = "Arid",
			Type = "Skin",
			Weapon = "Vector"
		},
		[30] = {
			Name = "Corrupted",
			Type = "Bottom"
		},
		[32] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_32"
		},
		[33] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "500",
			ID = "FreeS2_33"
		},
		[35] = {
			Name = "Isolation Carpet",
			Type = "Skin",
			Weapon = "M4A1"
		},
		[36] = {
			Name = "Pipeline",
			Type = "Banner"
		},
		[39] = {
			Name = "Isolation Carpet",
			Type = "Skin",
			Weapon = "G17"
		},
		[40] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_40"
		},
		[42] = {
			Name = "Detective",
			Type = "Head"
		},
		[43] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "500",
			ID = "FreeS2_43"
		},
		[44] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_44"
		},
		[45] = {
			Name = "Isolation Carpet",
			Type = "Skin",
			Weapon = "Desert Eagle 50 AE"
		},
		[48] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_48"
		},
		[49] = {
			Name = "Isolation Carpet",
			Type = "Skin",
			Weapon = "FAL"
		},
		[50] = {
			Name = "Detective",
			Type = "Top"
		},
		[52] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_52"
		},
		[53] = {
			Name = "Cash",
			Type = "Cash",
			Amount = "500",
			ID = "FreeS2_53"
		},
		[55] = {
			Name = "Isolation Carpet",
			Type = "Skin",
			Weapon = "Serbu Shotgun"
		},
		[56] = {
			Name = "PMC",
			Type = "Title"
		},
		[59] = {
			Name = "Isolation Carpet",
			Type = "Skin",
			Weapon = "MAC10"
		},
		[60] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_60"
		},
		[63] = {
			Name = "Detective",
			Type = "Bottom"
		},
		[64] = {
			Name = "Teddy",
			Type = "Charm"
		},
		[65] = {
			Name = "Sablehaze",
			Type = "Skin",
			Weapon = "Honey Badger"
		},
		[66] = {
			Name = "Credit",
			Type = "Credit",
			Amount = "300",
			ID = "FreeS2_66"
		},
		[68] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_68"
		},
		[69] = {
			Name = "Sablehaze",
			Type = "Skin",
			Weapon = "FAMAS"
		},
		[71] = {
			Name = "Sablehaze",
			Type = "Skin",
			Weapon = "TEC-9"
		},
		[72] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_72"
		},
		[76] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_76"
		},
		[77] = {
			Name = "Sablehaze",
			Type = "Skin",
			Weapon = "P90"
		},
		[80] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_80"
		},
		[83] = {
			Name = "Sablehaze",
			Type = "Skin",
			Weapon = "FN Minimi"
		},
		[85] = {
			Name = "Sablehaze",
			Type = "Skin",
			Weapon = "AS VAL"
		},
		[86] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_86"
		},
		[88] = {
			Name = "Sablehaze",
			Type = "Skin",
			Weapon = "MAC10"
		},
		[90] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_90"
		},
		[95] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_95"
		},
		[100] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_100"
		},
		[105] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_105"
		},
		[110] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_110"
		},
		[115] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_115"
		},
		[120] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_120"
		},
		[125] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_125"
		},
		[130] = {
			Name = "Regular",
			Type = "Crate",
			ID = "FreeS2_130"
		}
	}
}