
return {
    UpdateDate = 102,
    UpdateVerson = "15.0",
    Logs = {
        {
            Title = "Update 15.0 - Replay Kill Cam & More",
            Entries = { "- Added Replay Kill Cam", "- Replaced Concrete & Fabric footstep sfx", "- Extended Black Cell Event for 1 week", "- Throwables are no longer using Roblox physics for accuracy", "- Added Gas Station into map rotation", "- Casual matchmaking improved search time", "- Prioritise local region more for casual matchmaking", "- Broken sprinting bug fixed", "- Desert defender spotted area bug fixed", "- New CODE: REPLAYJAILBIRD", "- Black cell Head skin camera bug fixed", "- Barricade prompts are shown during spectate bug fixed", "- ", "", "" }
        },
        {
            Title = "Update 14.0 - Event, Balancing & Fixes",
            Entries = { "- New Event Black Cell", "- Weapon swapping bug fix", "- Spawning weapon delay fix", "- ADS walkspeed balancing (May revert)", "- ADS & Vault movement speed rebalancing", "- Movement/footsteps sound minor rework adjustments", "- Spectating first person bugs fixes", "- New code: BLACKCELL", "- Team rebalance vote", "- ", "", "" }
        },
        {
            Title = "Update 13.0 - Bunker map & Custom fixes",
            Entries = { "- Spectate graphics bug fixed", "- FOV range now between 70 to 90", "- Bunker new map", "- Custom map change fix", "- New code: JAILBIRDELITE", "", "" }
        },
        {
            Title = "Update 12.1 - FPP Post Update",
            Entries = { "- Despawn throwables every round", "- Spectate uses (Q,E) PC, (L1,R1) Console", "- Remove health, added device icon on spectator ui", "- Custom gamemode fixes & adjustments", "- FP Spectate uses your own FOV", "- FP Spectate animation fixes", "- Show damage screen effect while spectate", "- A brief death screen effect when plr dies", "- Matchmaking data leak fixes", "- Casual req Min 6 players to start a match", "- PROMOCODE: FIRSTPERSONPOSTUPDATE1", "", "" }
        },
        {
            Title = "Update 12.0 - FPP & Matchmaking",
            Entries = { "- Added First Person Perspective spectate", "- Matchmaking refix", "- Round time reduce by 10s", "- PROMOCODE: FIRSTPERSON", "", "" }
        },
        {
            Title = "Update 11.1 - Mostly Fixes",
            Entries = { "- Matchmaking fix", "- Ranked mode fix", "- Custom mode fix", "- Reduced latency explosion on impact & molotov", "- Grenade collision sound fix", "- Barricade breakable during prep fix", "", "" }
        },
        {
            Title = "Update 11.0 - Leaderboards & Miragon Map",
            Entries = { "- All time & Weekly Leaderboard", "- New Map Miragon", "- Another matchmaking patch release", "- Leaderboard now show username instead", "- Game end scene bug fixed", "- Adjusted weekly missions", "- Limited items will not be announced", "", "" }
        },
        {
            Title = "Update 10.4 - Fix",
            Entries = { "- Servers", "", "" }
        },
        {
            Title = "Update 10.3 - More fixes",
            Entries = { "Apologies for all the bugs! I\'ve been trying", "my best to fix them all, and still working on it.", "Here are some fixes", "- Sprint can cancel ADS now", "- Another match making patch released", "- Daily mission bug patch", "- Latency on mobile movements patched", "- Unable to barricade after dying fixed", "- Unable to break glasses fixed", "- Unable to queue with party patch", "- Mobile unable to turn while spectating", "", "" }
        },
        {
            Title = "Update 10.2 - Servers & More",
            Entries = { "- Slow matchmaking patch 1.0", "- Weapon optimisation rollout 1", "- Game optimisation rollout 2", "- Server side vault lag fix", "- Smoother movement patch", "- Proximity& Spikey grenade latency patch", "- Proximity now has 3 health", "- You can shoot down proximity alarm", "- Reduced kill latency/delay", "- Dropped hat/hair when ragdoll fixed", "- Look rotation error bug fixed", "- Barricading now will stop you from moving", "- Reworked barricade size/count", "- Bullet impact sound adjustments", "- Server animations fixes (Running/Barricading/Reload)", "- Prone/Crouch to Running has smoother transition", "- Faster weapon load when spawning", "- Ranked now will temporarily be 3rd person spectate", "due to first person rework is still work in progress", "- Votekick shows display name instead", "- Replaced blood with highlight damage", "- New code: OPTIMISATION", "", "" }
        },
        {
            Title = "Update 10.1 - Servers broken patch 1.0",
            Entries = { "Broken servers fix rollout", "New promocode \'SERVERFIX\'", "" }
        },
        {
            Title = "Update 10.0 - Systems, Crates & QoL",
            Entries = { "Added Rookie, Regular, and Elite crates", "Crates now use rolling open animations", "Daily and weekly missions now reward crates", "Reworked laser attachment behavior", "Added trajectory guides for throwables", "Applied weapon optimization and reduced low-level recoil", "Repolished the UI and improved loadout creation prompts", "Added spectator rewards and login rewards", "Added global announcements for legendary crate pulls", "Adjusted team balancing for fairer matchups", "Patched match server freeze issues", "Replaced the Jailbird logo", "Fixed mobile firing issues", "Fixed incorrect camera facing on spawn", "Fixed incorrect end-game titles", "Repolished loadout UI", "Mobile players can turn weapon on loadout", "", "" }
        },
        {
            Title = "Update 9.0 - CRIMSON EVENT & More",
            Entries = { "CRIMSON EVENT Scheduled on 22 May Stay tuned!", "Votekick and rebalance disabled after 4wins", "Removed delay before end game scene", "Auto teleport players to lobby after 20sec", "Casual servers does refresh fixed", "Slight changes on play page ui", "Reassigned regular crates", "Mobile loadout selection fixed", "Removed OJB Map", "Remodeled 4x Magnified for better ADS", "Reposition weird Holographic sights", "" }
        },
        {
            Title = "Update 8.7 - OJB MAP & Ranked Fixes",
            Entries = { "Ranked false abandoned fix", "OJB Map added for 1 day", "Loadout renamed fix", "Loadout main selectors will refresh immediately", "Vest can be unequipped when reselect", "" }
        },
        {
            Title = "Update 8.6 - Bug Fixes & Adjustments",
            Entries = { "Increased barricade dmg on Primary and nades", "Playerleft inaccurate amount fixed", "Blizzard map & Attacker spawn prompt fixed", "Reworked vest stats!", "Vector,P90 reduced barricade dmg", "Find Promocode claim in Store!", "New: SMILEYOVERHAUL, 80KLIKESJAILBIRD", "Another secret promocode! O_O", "Game server rare start failure fix", "Party max 5 players", "Rescale mobile game UI", "Repatched weapon spawn bug", "Gang fixes (Data, Invites, Other actions)", "Kill points feedback will accumulate", "Ranked level requirements warning", "Custom fixed", "You can now change loadouts in game", "" }
        },
        {
            Title = "Update 8.5 - OVERHAUL Update",
            Entries = { "Lobby UI & Ingame UI Overhaul", "Matchmaking improvements", "New reworked map Ascension", "Smoother match flow & gameplay experience", "Match end [Choose your reward] system", "Ranked 5v5 Casual 6v6" }
        },
        {
            Title = "Update 8.4 - CONTENT Update",
            Entries = { "New promocode: \'NEWCONTENT\'", "New Skirmish map: \'Construction\'", "2 new guns: AN-94 & K2C1", "3 new gun skins & 3 new character skins in Regular crate", "3 new gun skins & 3 new character skins in Group crate", "2 new sights: Rounded Holographic & Mini Plus Sight", "1 new Limited-Time Gamepass: Lovestruck" }
        },
        {
            Title = "Update 8.3 - QOL Update",
            Entries = { "New promocodes: \'QOLFIXES\' & \'NEWGUNSOUNDS\'", "New Map Changes: Office, Moon Base & Tokyo", "Gun sound changes Part 2: AKM, AS VAL, AKS-74U, M24, M40, MP5, MP5K, MP10, MP7, MCX, Vector, Mac-10, HK416, MK11, Honey Badger, L86 LSW, FAL, FAMAS, Minimi, PP-19-01, P250 (Quietened)", "Removed variable pitching in bullet shots, this should make gun sounds much better, even ones that haven\'t been changed", "Gun skin fix: Samurai Temple, Spooky Aurora, S5 Ranked Emperor, S5 Ranked Global, S5 Ranked Apex, Night Tropical, Bloodcrush, Aurora, Street Graffiti, Unix, Demon Fire, Street, Unknown, Radioactive, All Mosaic Royals, Devil Heart, Plague Flower", "Fixed some gun skin images not displaying correctly in skin selection tab", "Fixed Fluffy Torso colour not showing the correct tone" }
        },
        {
            Title = "Update 8.2 - SPOOKY UPDATE",
            Entries = { "New promocode: \'SPOOKY\'", "New Spooky Event & Mode", "1x Ka-Bar knife added to store rotation", "New LIMITED Gamepass: Hatchet (1x Hatchet Knife - 29 Robux)", "New LIMITED Gamepass: Silence (1x \'Silence\' Grand Skin & Universal Wasteland Gun Skin - 300 Robux)" }
        },
        {
            Title = "Update 8.1 - WINTER UPDATE",
            Entries = { "New promocodes: \'S5RELEASE\', \'70KLIKESJAILBIRD\', \'NEWYEAR\'", "New Winter Event", "New Map: Casino", "New gamepass: Dual Skin (Universal \'Ashfall\' & \'Pinkscale\' gun skins", "Some weapon and misc sound changes" }
        },
        {
            Title = "Update 8.0 - SEASON 5",
            Entries = { "New promocode: \'S5RELEASE\'", "New S5 Battlepass", "New Map: Station", "New Gamepass Bundle: Midnight Operator", "New Featured Knife & Skin in store: Combat", "New Attachment Skin system and progression update", "Reworked gun models for most guns", "Reworked many skins, rest of the skin reworks come another update", "Backend script overhaul", "Ranked is now 5v5", "Weapon rebalances", "Vest rebalance", "Slowed game pacing", "Fixed sometimes spawning outside the map", "Reduced blur and blood effect when shot" }
        },
        {
            Title = "Update 7.9 - Summerside Rework",
            Entries = { "New promocode: \'SUMMERSIDE\'", "New HIDDEN Promocode ;)", "Rework for Summerside Offices", "Changed Bunker to remove hatch above main stairs", "Fixed charms not showing up on the gun", "Lobby UI has been improved", "Fixed so that guns icons in the kill-feed are now completely white or black", "Fixed ONE of the many bugs where the camera would sometimes be stuck in the void", "Fixed random misc reported bugs", "Game description fixed and updated to remove outdated information" }
        },
        {
            Title = "Update 7.8 - Bugfixes & Skins",
            Entries = { "New Promocodes: \'NEWSKINS\' & \'MOREFIXES\'", "Added Driftline to Co-Op as an extra mission", "Added new characters and gun skins to regular crates", "Fixed Co-Op bots not moving when spawning on certain maps", "Made Co-Op bots less OP", "Moved Driftline Defender Spawn into defender objective", "Fixed Co-op Chapter 4 Mission 4 not being playable", "Fixed invisible gun glitch", "Fixed server region displaying \'Failed, Failed\'", "Improved anti cheat (Rip Bozo cheaters)", "Cleaned up code with better error and log handling", "Fixed bug where weapons with textures or different materials would not be completely white in the bottom right corner (Weapon UI)", "Micro optimized code to perform slightly better", "Fixed bug where invisible parts in co-op would block bullets" }
        },
        {
            Title = "Update 7.7 - CO-OP FIXES",
            Entries = { "New Promocodes: \'COOPFIX\' & \'DRIFTLINE\'", "New Map: Driftline (For Casual and Ranked playlists)", "Fixed bug with the sniper scopes not being centered", "Fixed bug where killing co-op bots with grenades would soft lock the game", "Fixed bug which caused spawn location billboards to not appear", "Improved anti-cheat", "Added a click sound when you are trying to shoot without ammo", "Fixed atmosphere blocking the map view when selecting spawn location", "Fixed console error spam" }
        },
        {
            Title = "Update 7.6 - BUGFIXES",
            Entries = { "New Promocode: \'BOOSTED\'", "Two new maps: Safehouse & Birdian Mall (For Arcade Elimination Mode)", "Bug fixes to Cargo: spawning stuck, & spawning outside issues", "Improvements to the Anti-Cheat", "Restored global ban pop-ups", "New Mode has been pushed back another week" }
        },
        {
            Title = "Update 7.5 - QOL UPDATE",
            Entries = { "New Promocodes: \'QOLUPDATE\' & \'GRINDINGTIME\'", "New map: Trenches - For Skirmish modes", "Hardpoint and Domination now have improved UI", "Hardpoint and Domination spawn system improvements", "Fixed some issues with strange hitboxes in Havana & Railway", "Added Cargo, Cluster Camp, & Shoot House to Domination & Hardpoint", "Hardpoint and Domination now have improved UI", "The Hardpoint now loops through set points, this should help Hardpoint play smoother and be more reliable", "Fixed multiple bugs", "Changes have been made to Cargo only for Domination & Hardpoint modes" }
        },
        {
            Title = "Update 7.4 - Skirmish Update",
            Entries = { "New Promocode: SKIRMISHUPDATE", "New Gamemodes: Hardpoint & Domination (Both inside Skirmish)", "Two new maps: Railway & Havana (Only for Hardpoint, Domination & Raid)", "Backend Improvements" }
        },
        {
            Title = "Update 7.3 - GUNS UPDATE",
            Entries = { "New Promocode: NEWGUNS", "4 New guns (MCX, PP-19-01, P250, Uzi)", "4 New attachments (1 Scope, 2 Grips, 1 Silencer)", "Major gun rebalancing", "Skippable intro screen by pressing space (PC), or A (Controller)", "Co-Op Returns", "New Event", "New Grand Pass - Goldsune (649 R$)" }
        },
        {
            Title = "Update 7.2 - BUG PATCH",
            Entries = { "New Promocode: BUGFIXES", "Added AFK as a new kick reason", "Changes to Airport for better balancing", "Fixed an issue causing Sniper rifles to be loud and heard from across the map", "Fixed a issue with the FN-MiniMe model not fully removing the iron sights when applying an optic", "Fixed a bug with the UI causing highlighted text to not return to its original colour", "Fixed a bug that caused dead bodies to error and not hide other dead bodies", "Fixed a bug with the anti-cheat", "Fixed multiple weapon system bugs", "Fixed a bug relating to the in-game UI", "Fixed the Challenge UI not sufficiently using it\'s space" }
        },
        {
            Title = "Update 7.1 - MAJOR BUG FIXES!",
            Entries = { "New Promocode: JAILBIRD2025", "New Map: Airport - Casual and Ranked playlists", "Added keybinds (keybinds menu in lobby and in game along with a visualizer for controller and keyboard inputs)", "Added sensitivity modifier + dedicated aim sensitivity", "Added account minimum age requirement (3 days)", "Dead characters disappear after around ~5 seconds", "Migrated to Roblox new chat API", "Added chat translation to different languages", "Added Server location to the scoreboard", "Fixed a bug that prevents you from being given weapons at the start of a match", "Fixed a bug that makes you die before spawning", "Fixed bug where first person arms would not match skin colour", "Small performance issues fixed" }
        },
        {
            Title = "Update 7.0 - SEASON 4!",
            Entries = { "New Season 4 Battlepass", "Two New Maps: Tokyo & Blizzards Keep", "New Featured Knife and Skin: Cyber Fighter & Etherial", "New Event: Worlds Collide", "New Weapon balancing changes", "New weapon skins in the store and in Daily Crates. Regular crates have both new Characters and Weapon Skins", "Someone is laying hints around.. perhaps there\'s a secret code?", "New Glitch Grand Skin Bundle", "Fixed AKM & PPSH\'s Sight parts not being correctly positioned", "Fixed PPSH Mag not animating properly when reloading", "Fixed a bug that allowed players to leave the defender zone on Office before the round started", "Ranked Reopened: New Ranked Rewards", "New code: S4RELEASE" }
        },
        {
            Title = "Update 6.0",
            Entries = { "3 Primary Weapons", "Co-op Gamemode", "Co-op Points currency", "New throwable", "New OG Map return (Renovation)", "Map Rotation | Warehouse fix", "Glowing Charm lag patched 1.0", "New 50KLikes code check in Discord" }
        },
        {
            Title = "Update 5.2",
            Entries = { "Warehouse Returns for Casual and Ranked!", "2 OG Arcade Maps Return!", "Training Ground Rework", "New Ban System (Alt Detection)", "Sliding floor bug fix", "Impact grenades breaking windows before the match starts fix", "New 40KLIKESJAILBIRD Promocode", "Missing weapon bug patch" }
        },
        {
            Title = "Update 5.1",
            Entries = { "3 OG Maps Return: Checkpoint, Desert & Summerside Offices!", "New Nyx Gamepass bundle!", "New Workshop feature in the store, you can now use your hard-earned cash on skins and characters!", "New throwables: Impact Grenade, Proximity Alarm, & Tear Gas", "Weapon & Grenade rebalancing", "Spawn Rework v1 (Hopefully this stops dying or flinging on spawn)", "Miragon & Ascension grenade spawnkill fixed", "Ranked minimum level increased to 15+", "Flashbang now flashes enemies", "Game pass missing weapon skins FIXED! SORRY!" }
        },
        {
            Title = "Update 5.0: SEASON 3!",
            Entries = { "New battlepass: 5 Characters, 6 weapon skins, 4 charms, 3 titles, 4 banners", "New knife: Karambit & two Karambit skins!", "New Karambit animations for inspect and melee", "1 new Featured skin & 1 new featured Karambit skin", "Ranked has been re-opened", "New map: GOVERNED for Ranked and Casual playlists", "Outlands added to ranked playlist", "New codes: \'S3RELEASE\' & \'30KLIKESJAILBIRD\', Thanks for your support!", "Fling Patch V1: Expanded spawns to hopefully prevent flinging", "Missing Weapon Patch V1", "Anti-Spawnkill Updates to Workspace & Gas Station", "Shooting optimization", "Performance setting", "Client-Sided spotted outside indication" }
        },
        {
            Title = "4.6",
            Entries = { "NEW MAP: Outlands", "Fixed bugs causing attackers to spawn in defender zones within moonbase", "Raised the brightness in Nebula", "Max FOV raised to 100" }
        },
        {
            Title = "4.5 Event Update: OPERATION NEBULA",
            Entries = { "Nebula Event live! Earn rewards by playing", "NEW MAPS: Nebula & Moon base", "New knife skins & Character skins!" }
        },
        {
            Title = "4.0 MAJOR UPDATE (MAY)",
            Entries = { "Weapon system reworked | Recoil | Animations", "Vault System", "Knife system/ Throwable holster", "Sights reworked", "Items duplicate", "Starterpack", "Booster extended to 1 hour", "New Grand skin", "New Lobby loadout system", "Match making system reworked", "New match server lists (Separate gamemodes)", "New sound cues reworked", "Equipment HUD for keybinds 1 - 4", "Bugs fixes", "Some weapon stats readjustments", "Credits currency Bonus in shop", "PROMOCODE IN COMMUNITY SERVER", "Map Adjustments | Workspace", "Player Highlight transparency settings", "Lighter objective UI", "And MORE!" }
        },
        {
            Title = "NEW CODE FOR 20K LIKES! - Can be found in our official Discord server",
            Entries = {}
        },
        {
            Title = "3.5",
            Entries = { "Temporary broken server matchmake fixes", "Matches with overloaded players bug patched 1.0 (Experimental)", "Server list will update more frequently | Matchpoint matches will not be joinable", "Arcade server list will sync map image" }
        },
        {
            Title = "3.4",
            Entries = { "New map ASCENSION", "New primary weapon SPAS-12", "New featured skin TEMPEST" }
        },
        {
            Title = "3.3",
            Entries = { "Weapon swap zero latency, instant switch | Infinite ammo patch 2.0", "[MIRAGON] Roof glitch patched | Standardised doorway sizes | Added clouds on prep phase", "SCAR | Increased fire rate and barricade damage", "Added VC", "Added Future update page in Home" }
        },
        {
            Title = "3.2",
            Entries = { "Weapon swap taking too long bug fixed", "New map MIRAGON" }
        },
        {
            Title = "3.1",
            Entries = { "Daily rewards fixed | Ranked match from casual queue bug fixed", "Party leave button patched 1.0", "Bullets not damaging bug fixed | Stealth and Challenger badge bug fixed", "Reorder attacker spawn prompt for Sand Fort, Gas Station, Gemstone", "Faster teleport to Lobby after end game | Nova Mag +2 capacity", "New kill hitmarker | New teleport transition screen", "Console prone fixed | Character rotate weirdly when sprinting first time patched", "Detected controller on mobile will deactivate mobile controls" }
        },
        {
            Title = "3.0",
            Entries = { "Season 2 | Ranked Rewards | New Battlepass 130 Tiers! | Season Featured Character skin", "UI Rework | Attacker prompt rework", "Daily reward system | New Daily crate", "Lots of bugs fixed", "[SKIRMISH] Protective team barrier | Minor changes to all Skirmish maps", "More new items in Store | Better randomization", "Charm lightings (Glowing)", "Ranked / Profile page rework | Added Ranked rewards page", "Player HUD Reworked", "[CASUAL] Hideout map reworked", "Gang Delete/Promote/Demote functions | Gang TOS | More Gang Icon presets", "[THROWABLES] New Frost Smoke", "+ More update logs | Can be found in Discord" }
        }
    }
};