
return {
    Position = { "CFrame" },
    Orientation = { "CFrame" },
    Color = { "Color3" },
    Rotation = { "CFrame", "Orientation" },
    BackgroundColor = { "BackgroundColor3" },
    TextColor = { "TextColor3" },
    WorldPosition = { "CFrame" },
    WorldCFrame = { "CFrame" },
    WorldAxis = { "Orientation" },
    WorldSecondaryAxis = { "Orientation" },
    Axis = { "Orientation" },
    SecondaryAxis = { "Orientation" }
};